/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/space_ship_mk2-transformed.glb 
Author: antoniojmonteiro (https://sketchfab.com/antoniojmonteiro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-mk2-c361eff050d64c149ca44ab8e6c09390
Title: Space Ship mk2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/space_ship_mk2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Material4.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.Metal_Silver} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material3.geometry} material={materials.Translucent_Glass_Tinted} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
    </group>
  )
}

useGLTF.preload('/space_ship_mk2-transformed.glb')
