/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF } from '@react-three/drei';

// Dòng này là thứ quan trọng nhất, nó export component mặc định
export default function Model(props) {
  // Đường dẫn này phải trỏ đến file model đã được tối ưu
  const { nodes, materials } = useGLTF('/models/hi-transformed.glb');
  
  // Lưu ý: Cấu trúc JSX bên trong return này có thể khác
  // tùy thuộc vào model của bạn. Nhưng phần khung bên ngoài là đúng.
  return (
    <group {...props} dispose={null}>
      {/* Ví dụ về cách render một phần của model. 
          Công cụ gltfjsx sẽ tự tạo ra phần này cho bạn.
          Nếu model không hiện, có thể do cấu trúc này chưa khớp.
          Nhưng lỗi import sẽ được khắc phục trước.
      */}
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
    </group>
  );
}

// Dòng này giúp Preload model để không bị giật lag
useGLTF.preload('/models/hi-transformed.glb');