/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

// ĐÂY LÀ ĐƯỜNG DẪN ĐÚNG SAU KHI BẠN ĐÃ DI CHUYỂN FILE
const modelPath = '/models/space_ship_mk2-transformed.glb'

export function Model(props) {
  const { nodes, materials } = useGLTF(modelPath)
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Material4.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.Metal_Silver} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material3.geometry} material={materials.Translucent_Glass_Tinted} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.002, 0.002, 0.002]} />
    </group>
  )
}

useGLTF.preload(modelPath)

// Để tránh các lỗi sau này, chúng ta sẽ thêm export default
export default Model